# FILL IN THE MISSING VALUES BELOW
alerting:
  ???:
    token: "<github-token>" # WARN: DO NOT CHANGE THIS LINE
# FILL IN THE MISSING VALUES ABOVE

# FILL IN THE MISSING VALUES BELOW
endpoints:
  - name: Leantime
    url: <leantime-url> # WARN: DO NOT CHANGE THIS LINE
    interval: 30s # WARN: DO NOT CHANGE THIS LINE
    conditions:
      - type: "status_code"
        expected: 200
        message: "Leantime is down! Please check and fix it."
      - type: "response_time"
        threshold: 1000 # milliseconds
        message: "Leantime is slow! Please check and fix it."
      - type: "keyword"
        keyword: "Leantime"
        message: "Leantime is not responding as expected! Please check and fix it."
    conditions:
    alerts:
      - type: ???
        description: "Sensei, Leantime is down! Please check and fix it."

  - name: Gatus
    url: <gatus-url> # WARN: DO NOT CHANGE THIS LINE
    interval: 60s # seconds
    conditions:
      - type: "status_code"
        expected: 200
        message: "Gatus is down! Please check and fix it."
      - type: "response_time"
        threshold: 1000 # milliseconds
        message: "Gatus is slow! Please check and fix it."
      - type: "keyword"
        keyword: "Gatus"
        message: "Gatus is not responding as expected! Please check and fix it."
    conditions:
    alerts:
      - type: ???
        description: "Sensei, Gatus is down! Please check and fix it."
# FILL IN THE MISSING VALUES BELOW
